name: hello-world
on: [push]
jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
       - name: Hello world action
         env: 
           SUPER_SECRET: ${{ secrets.mysecret }}
         run: echo "And the secret is $SUPER_SECRET" 
       #checkout
       - uses: actions/checkout@v4
         with:
           sparse-checkout: |
             index.html
           sparse-checkout-cone-mode: false
       - name: Encrypt pages with PageCrypt
         run: |
          npm i -D pagecrypt
          sudo npx pagecrypt index.html index.html ${{ secrets.mysecret }}
          # End encryption
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v1
         with:
          path: ./
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
      
    steps:
      - name: Deploy to GitHub Pages
      - id: deployment
      - uses: actions/deploy-pages@main          

  
