name: hello-world
on: [push]
jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
       - name: Hello world action
         env: 
           super_secret: ${{ secrets.secret }}
         run: echo "And the secret is $super_secret"  
