name: hello-world
on: [push]
jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
       - name: Hello world action
         with: 
           SUPER_SECRET: ${{ secrets.mysecret}}
         run: echo "And the secret is $SUPER_SECRET"  
